#frontend/Dockerfile
FROM node:18 AS build

#set working directory
WORKDIR /app

#Install dependencies
COPY package*.json ./
RUN npm install

#copy app source
COPY . .

#Build the react app
RUN npm run build

#server the build with nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html

#copy nginx.conf /etc/nginx/nginx.conf
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]