# backend / dockerfile
FROM node:18

#create app directory
WORKDIR /app

#Install dependencies
COPY  package*.json ./
RUN npm install

#copy the rest of the code 
COPY . .

#Expose backend port 
EXPOSE  8080

#Start the backend server
CMD ["node", "index.js"]
